config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users
  root to: "home#index"
  resources :participacaos

  resources :convocados

  resources :item_pauta

  resources :reuniaos

  resources :sugestao_item_pauta

  resources :ata

  resources :locals

  resources :pauta

  resources :questaos

  resources :pontos

  resources :pessoas

end

app/models/participacao.rb
class Participacao < ActiveRecord::Base
  belongs_to :pessoa
  belongs_to :reuniao
 def self.search(query1,query2)



     #where(['pessoa_id =:query1 AND reuniao_id = :query2', query1:"%#{query1}%", query2:"%#{query2}%"])
      where(['pessoa_id = :query1 AND reuniao_id = :query2',query1: query1, query2: query2])
           #where(["pessoa_id = :query", query1: query1])
     #where(["pessoa_id = :query1 AND reuniao_id = :query2",query1,query2])
   
  end

end

app/controllers/participacaos_controller.rb
class ParticipacaosController < ApplicationController
  load_and_authorize_resource
  before_action :set_participacao, only: [:show, :edit, :update, :destroy]

  # GET /participacaos
  # GET /participacaos.json
  def index
    @participacaos = Participacao.all
  end

  # GET /participacaos/1
  # GET /participacaos/1.json
  def show
  end

  # GET /participacaos/new
  def new
    @participacao = Participacao.new
    if params[:reuniao]
        @participacao.reuniao = Reuniao.find(params[:reuniao])
     end
  end

  # GET /participacaos/1/edit
  def edit
  end

  # POST /participacaos
  # POST /participacaos.json
  def create

    respond_to do |format|
      aux= params[:participacao][:pessoa_id]
     if aux.size > 1


      for x in aux
            if x == ""
                 break#a ultima posição do array e um "" e isso não é um id por tanto da erro entao esse if resolve isso
            end
            @pessoa=Pessoa.find(x) #aqui eupego a pessoa com o id q ta no x

            @participacao = Participacao.new(participacao_params)#colocando o new dentro for me permite fazer varias participacao com id diferentes o que evida erro se o id foce o mesmo nao seria create e sim update de fk de pessoa   
            @reuniao = Reuniao.find(@participacao.reuniao) 

            if Participacao.search(@pessoa.id, @reuniao.id) == []  #com esse if eu evito que se convoque a mesma pessoa 2 vezes
               @participacao.pessoa=@pessoa# passo o objeto para convocado
               @participacao.save
            end

      end
      @reuniao = Reuniao.find(@participacao.reuniao) 


        format.html { redirect_to @reuniao, notice: 'Participacao was successfully created.' }
        format.json { render :show, status: :created, location: @reuniao }
        
    else


            format.html { redirect_to reuniao_path(@participacao.reuniao), notice: 'Desculpe mas,você não selecionou ninguem.' }
         end
    end
  end

  # PATCH/PUT /participacaos/1
  # PATCH/PUT /participacaos/1.json
  def update
    respond_to do |format|
      if @participacao.update(participacao_params)
        format.html { redirect_to @participacao, notice: 'Participacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @participacao }
      else
        format.html { render :edit }
        format.json { render json: @participacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participacaos/1
  # DELETE /participacaos/1.json
  def destroy
    @aux=@participacao
    @participacao.destroy
    respond_to do |format|
      format.html { redirect_to reuniao_path(@participacao.reuniao), notice: 'Participacão foi removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participacao
      @participacao = Participacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participacao_params
      params.require(:participacao).permit(:contribuicao, :pessoa_id, :reuniao_id)
    end
end

app/helpers/participacaos_helper.rb
module ParticipacaosHelper
end

app/views/participacaos/_form.html.erb
<%= form_for(@participacao) do |f| %>
  <% if @participacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participacao.errors.count, "error") %> prohibited this participacao from being saved:</h2>

      <ul>
      <% @participacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :pessoa_id %><br>
    <%= f.collection_check_boxes(:pessoa_id, Pessoa.order(:nome),:id, :nome, :prompt => true) %>
  </div>
  <div class="field">


        <%= f.hidden_field 'reuniao_id' %>
  </div>
  <div class="actions">
    <%= f.submit "Cadastrar Participantes" %>
  </div>
<% end %>

app/views/participacaos/edit.html.erb
<h1>Editar Participação</h1>

<%= form_for(@participacao) do |f| %>
  <% if @participacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participacao.errors.count, "error") %> prohibited this participacao from being saved:</h2>

      <ul>
      <% @participacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contribuicao %><br>
    <%= f.text_area :contribuicao %>
  </div>

  <div class="field">
    <%= f.label :reuniao_id %><br>

        <%= f.hidden_field 'reuniao_id' %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar Participação"%>
  </div>
<% end %>

app/views/participacaos/index.html.erb
<h1>Listing participacaos</h1>

<table>
  <thead>
    <tr>
      <th>Contribuicao</th>
      <th>Pessoa</th>
      <th>Reuniao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participacaos.each do |participacao| %>
      <tr>
        <td><%= participacao.contribuicao %></td>
        <td><%= participacao.pessoa %></td>
        <td><%= participacao.reuniao %></td>
        <% if can? :read, @participacao %>
        <td><%= link_to 'Show', participacao %></td>
    <% end %>
        <% if can? :update, @participacao %>
        <td><%= link_to 'Edit', edit_participacao_path(participacao) %></td>
    <% end %>
        <% if can? :delete, @participacao %>
        <td><%= link_to 'Destroy', participacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
        <% if can? :update, @participacao %>
<%= link_to 'New Participacao', new_participacao_path %>
    <% end %>

app/views/participacaos/new.html.erb
<h1>Inserir participantes</h1>

<%= render 'form' %>

app/views/participacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contribuicao:</strong>
  <%= @participacao.contribuicao %>
</p>

<p>
  <strong>Pessoa:</strong>
  <%= @participacao.pessoa %>
</p>

<p>
  <strong>Reuniao:</strong>
  <%= @participacao.reuniao %>
</p>
        <% if can? :update, @participacao %>
<%= link_to 'Edit', edit_participacao_path(@participacao) %> |
        <% end %>
<%= link_to 'Back', participacaos_path %>