config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users
  root to: "home#index"
  resources :participacaos

  resources :convocados

  resources :item_pauta

  resources :reuniaos

  resources :sugestao_item_pauta

  resources :ata

  resources :locals

  resources :pauta

  resources :questaos

  resources :pontos

  resources :pessoas

end

app/models/questao.rb
class Questao < ActiveRecord::Base
  belongs_to :pessoa
  has_many :pontos
  belongs_to :user
 has_many :item_pautums

  #scope :buscaPessoa, lambda {|query| where("pessoa_id == ? ", query )}

  def self.buscaPessoa(query)

   if query.present? 

           where(["pessoa_id = :query", query: query])
   else
      where(['data LIKE ""', query:"%#{""}%"])
   end
  end


 # scope :buscaQuestao, lambda {|query| where("titulo LIKE  ? ", query )}

  def self.buscaQuestao(query)
   if query.present? 
      where(['titulo LIKE :query ', query:"%#{query}%"])
   else
      where(['data LIKE ""', query:"%#{""}%"])
   end
end
end

app/controllers/questaos_controller.rb
class QuestaosController < ApplicationController
  load_and_authorize_resource
  before_action :set_questao, only: [:show, :edit, :update, :destroy]

  # GET /questaos
  # GET /questaos.json
  def index
if params[:q] !=nil
    @pessoa=Pessoa.buscaMatricula(params[:q]) 
   if @pessoa != []  
    puts "passoooooooooooooo"
    @questaos = Questao.buscaPessoa(@pessoa[0].id)
else 
    @questaos= []
   end
else


    @questaos = Questao.buscaQuestao(params[:p])

end

    respond_to do |format|
      format.html  #index.html.erb
      format.xml  { render :xml => @questaos }
    end
  end

  # GET /questaos/1
  # GET /questaos/1.json
  def show
  end

  # GET /questaos/new
  def new
    @questao = Questao.new
    #@questao.find(params[:questao_id])

  end

  # GET /questaos/1/edit
  def edit
  end

  # POST /questaos
  # POST /questaos.json
  def create
    @user = current_user
    @pessoa=Pessoa.search(@user.id)

    @questao = Questao.new(questao_params)
    @questao.pessoa=@pessoa[0]
    @questao.user=@user
    

    respond_to do |format|
      if @questao.save
        format.html { redirect_to @questao, notice: 'Questao was successfully created.' }
        format.json { render :show, status: :created, location: @questao }
      else
        format.html { render :new }
        format.json { render json: @questao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questaos/1
  # PATCH/PUT /questaos/1.json
  def update
    @user = current_user
    if @user == @questao.user


    
    respond_to do |format|
      if @questao.update(questao_params)
        format.html { redirect_to @questao, notice: 'Questao was successfully updated.' }
        format.json { render :show, status: :ok, location: @questao }
      else
        format.html { render :edit }
        format.json { render json: @questao.errors, status: :unprocessable_entity }
      end
    end
    else
            redirect_to @questao , notice: 'Desculpe mas,está questão não é sua.'
   end
  end

  # DELETE /questaos/1
  # DELETE /questaos/1.json
  def destroy
    @user = current_user
    if @user == @questao.user
    @questao.destroy
    respond_to do |format|
      format.html { redirect_to questaos_url, notice: 'Questao was successfully destroyed.' }
      format.json { head :no_content }
    end
end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questao
      @questao = Questao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questao_params
      params.require(:questao).permit(:titulo, :data, :status, :solucao, :pessoa_id)
    end
end

app/helpers/questaos_helper.rb
module QuestaosHelper
end

app/views/questaos/_busca.html.erb
<%= form_tag(questaos_path, :method => "get") do %>

  <%= label_tag(:search_query, "Titulo:") %>
  <%= text_field_tag :p, @search_query %>
  <%= submit_tag("Buscar") %>



<% end %>

app/views/questaos/_form.html.erb
<%= form_for(@questao) do |f| %>



  <% if @questao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questao.errors.count, "error") %> prohibited this questao from being saved:</h2>

      <ul>
      <% @questao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_area :titulo %>
  </div>

  <div class="field">


        <%= f.hidden_field 'pessoa_id' %>
  </div>
  <div class="actions">
    <%= f.submit "Cadastrar Pessoa"%>
  </div>
  
<% end %>

app/views/questaos/_matricula.html.erb
<%= form_tag(questaos_path, :method => "get") do %>

  <%= label_tag(:search_query, "matricula:") %>
  <%= number_field_tag :q, @search_query %>
  <%= submit_tag("Buscar") %>



<% end %>

app/views/questaos/_pontos.html.erb
<% @questao.pontos.each do |ponto|  %>
<p>    
 <strong>Titulo:</strong>
	<%= ponto.titulo %>
</p>


<p>
        <% if can? :update, @ponto %>
	<%= link_to 'Editar', edit_ponto_path(ponto) %>
    <% end %>
        <% if can? :delete, @ponto %>
        <td><%= link_to 'Remover', ponto, method: :delete%></td>
    <% end %>
</p>
<p>


</p>

<% end %>

app/views/questaos/_search.html.erb
<% @questao.pontos.each do |ponto|  %>
<p>    
 <strong>Titulo:</strong>
	<%= ponto.titulo %>
</p>


<p>
        <% if can? :update, @ponto %>
	<%= link_to 'Editar', edit_ponto_path(ponto) %>
    <% end %>
        <% if can? :delete, @ponto %>
        <td><%= link_to 'Remover', ponto, method: :delete%></td>
    <% end %>
</p>
<p>


</p>

<% end %>

app/views/questaos/edit.html.erb
<h1>Editing questao</h1>

<%= render 'form' %>

<%= link_to 'Show', @questao %> |
<%= link_to 'Back', questaos_path %>

app/views/questaos/index.html.erb
<h1>Lista de questões</h1>
<%= render 'busca' %>
<%= render 'matricula' %>
<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Data</th>

      <th>Pessoa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questaos.each do |questao| %>
      <tr>
        <td><%= questao.titulo %></td>
        <td><%= questao.created_at.strftime("%d/%m/%Y") %></td>

        <td><%= questao.pessoa.nome %></td>
        <% if can? :read, @questao %>
        <td><%= link_to 'Exibir', questao %></td>
    <% end %>
        <% if can? :update, @questao %>
        <td><%= link_to 'Editar', edit_questao_path(questao) %></td>
    <% end %>
        <% if can? :delete, @questao %>
        <td><%= link_to 'Remover', questao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
        <% if can? :create, @questao %>
<%= link_to 'Cadastrar Questão', new_questao_path %>
    <% end %>

app/views/questaos/new.html.erb
<h1>Cadastro de questão</h1>

<%= render 'form' %>

app/views/questaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @questao.titulo %>
</p>

<p>
  <strong>Data:</strong>
  <%= @questao.created_at.strftime("%d/%m/%Y") %>
</p>



<p>
  <strong>Pessoa que criou esta questão:</strong>
  <%= @questao.pessoa.nome %>
</p>

        <% if can? :update, @questao %>
<%= link_to 'Editar', edit_questao_path(@questao) %> 
    <% end %>


<h1>Pontos</h1>
<%= render'pontos' %>

        <% if can? :create, @ponto %>
<%= link_to "Novo Ponto", controller: "pontos",
action: "new",
questao: @questao %>
    <% end %>