config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users
  root to: "home#index"
  resources :participacaos

  resources :convocados

  resources :item_pauta

  resources :reuniaos

  resources :sugestao_item_pauta

  resources :ata

  resources :locals

  resources :pauta

  resources :questaos

  resources :pontos

  resources :pessoas

end

app/models/ponto.rb
class Ponto < ActiveRecord::Base
  belongs_to :questao
  validates_presence_of :titulo
  scope :buscarPonto, lambda {|questao| where("questao_id == ? ", questao )}
end

app/controllers/pontos_controller.rb
class PontosController < ApplicationController
  load_and_authorize_resource
  before_action :set_ponto, only: [:show, :edit, :update, :destroy]

  # GET /pontos
  # GET /pontos.json
  def index
    @pontos = Ponto.all
  end

  # GET /pontos/1
  # GET /pontos/1.json
  def show
  end

  # GET /pontos/new
  def new
    @ponto = Ponto.new
    if params[:questao]
        @ponto.questao = Questao.find(params[:questao])
     end
  end

  # GET /pontos/1/edit
  def edit
  end

  # POST /pontos
  # POST /pontos.json
  def create
    @ponto = Ponto.new(ponto_params)
    @user = current_user
    if @user == @ponto.questao.user

    respond_to do |format|
      if @ponto.save
        format.html { redirect_to questao_path(@ponto.questao), notice: 'Ponto cadastrado.' }
        format.json { render :show, status: :created, location: @ponto }
      else
        format.html { render :new }
        format.json { render json: @ponto.errors, status: :unprocessable_entity }
      end
    end
else
            redirect_to questao_path(@ponto.questao) , notice: 'Desculpe mas,está questão não é sua.'
end
  end

  # PATCH/PUT /pontos/1
  # PATCH/PUT /pontos/1.json
  def update
    @user = current_user
    if @user == @ponto.questao.user
    respond_to do |format|
      if @ponto.update(ponto_params)
        format.html { redirect_to questao_path(@ponto.questao), notice: 'Ponto was successfully updated.' }
        format.json { render :show, status: :ok, location: @ponto }
      else
        format.html { render :edit }
        format.json { render json: @ponto.errors, status: :unprocessable_entity }
      end
    end
else
            redirect_to questao_path(@ponto.questao) , notice: 'Desculpe mas,está questão não é sua.'
end
  end

  # DELETE /pontos/1
  # DELETE /pontos/1.json
  def destroy
    @user = current_user
    if @user == @ponto.questao.user
    @ponto.destroy
    respond_to do |format|
      format.html { redirect_to questao_path(@ponto.questao), notice: 'Ponto removido.' }
      format.json { head :no_content }
    end
else
            redirect_to questao_path(@ponto.questao) , notice: 'Desculpe mas,está questão não é sua.'
end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ponto
      @ponto = Ponto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ponto_params
      params.require(:ponto).permit(:titulo, :data, :staus, :solucao, :questao_id)
    end
end

app/helpers/pontos_helper.rb
module PontosHelper
end

app/views/pontos/_form.html.erb
<%= form_for (@ponto) do |f| %>

  <% if @ponto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ponto.errors.count, "error") %> prohibited this ponto from being saved:</h2>

      <ul>
      <% @ponto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_area :titulo %>
  </div>


  <div class="field">


        <%= f.hidden_field 'questao_id' %>

  </div>
  <div class="actions">
    <%= f.submit "Cadastrar Ponto"%>
  </div>
<% end %>

app/views/pontos/edit.html.erb
<h1>Editar ponto</h1>

<%= render 'form' %>

app/views/pontos/index.html.erb
<h1>Listing pontos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Data</th>
      <th>Staus</th>
      <th>Solucao</th>
      <th>Questao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pontos.each do |ponto| %>
      <tr>
        <td><%= ponto.titulo %></td>
        <td><%= ponto.data %></td>
        <td><%= ponto.staus %></td>
        <td><%= ponto.solucao %></td>
        <td><%= ponto.questao %></td>
        <% if can? :read, @ponto %>
        <td><%= link_to 'Exibir', ponto %></td>
    <% end %>
        <% if can? :update, @ponto %>
        <td><%= link_to 'Editar', edit_ponto_path(ponto) %></td>
    <% end %>
        <% if can? :delete, @ponto %>
        <td><%= link_to 'Remover', ponto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
        <% if can? :create, @ponto %>
<%= link_to 'Novo Ponto', new_ponto_path %>
    <% end %>

app/views/pontos/new.html.erb
<h1>Novo ponto</h1>

<%= render 'form' %>

app/views/pontos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @ponto.titulo %>
</p>

<p>
  <strong>Data:</strong>
  <%= @ponto.data %>
</p>

<p>
  <strong>Staus:</strong>
  <%= @ponto.staus %>
</p>

<p>
  <strong>Solucao:</strong>
  <%= @ponto.solucao %>
</p>

<p>
  <strong>Questao:</strong>
  <%= @ponto.questao %>
</p>
        <% if can? :update, @ponto %>
<%= link_to 'Edit', edit_ponto_path(@ponto) %> |
    <% end %>
<%= link_to 'Back', pontos_path %>