config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users
  root to: "home#index"
  resources :participacaos

  resources :convocados

  resources :item_pauta

  resources :reuniaos

  resources :sugestao_item_pauta

  resources :ata

  resources :locals

  resources :pauta

  resources :questaos

  resources :pontos

  resources :pessoas

end

app/models/reuniao.rb
class Reuniao < ActiveRecord::Base
  belongs_to :local
  belongs_to :pautum
  belongs_to :atum
  belongs_to :category
  has_many :convocados
  has_many :participacaos
  has_many :sugestao_item_pautums
  
  Status =%w[cancelada aprovada Preparação]
  validates_presence_of :titulo,:category
  scope :created_between, lambda {|start_date, end_date| where("data >= ? AND data <= ?", start_date, end_date )}

  scope :buscarAta, lambda {|ata| where("atum_id == ? ", ata )}


  def self.buscaTitulo(query)

   if query.present? 
      where(['titulo LIKE :query OR data LIKE :query', query:"%#{query}%"])
   else
      where(['data LIKE ""', query:"%#{""}%"])
   end
  end


end

app/controllers/reuniaos_controller.rb
class ReuniaosController < ApplicationController 
  load_and_authorize_resource
  before_action :set_reuniao, only: [:show, :edit, :update, :destroy]

  # GET /reuniaos
  # GET /reuniaos.json
  def index

if params[:q] !=nil

    @reuniaos = Reuniao.created_between(params[:q],params[:o])


else
    @reuniaos = Reuniao.buscaTitulo(params[:p])
    #@pessoa = Pessoa.all
end



    #@reuniaos=Reuniao.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reuniaos }
    end
   
  end

  # GET /reuniaos/1
  # GET /reuniaos/1.json
  def show
  end

  # GET /reuniaos/new
  def new
    @reuniao = Reuniao.new
  end

  # GET /reuniaos/1/edit
  def edit
  end

  # POST /reuniaos
  # POST /reuniaos.json
  def create
    @reuniao = Reuniao.new(reuniao_params)
    @pautum=Pautum.new
    @reuniao.pautum =@pautum
    @reuniao.atum=Atum.new
    @reuniao.status="Preparação"
    @pautum.status="Preparação"
    
    respond_to do |format|
      if @reuniao.save
    @pautum.titulo=@reuniao.titulo
    @pautum.save
        format.html { redirect_to @reuniao, notice: 'Reuniao was successfully created.' }
        format.json { render :show, status: :created, location: @reuniao }
      else
        format.html { render :new }
        format.json { render json: @reuniao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reuniaos/1
  # PATCH/PUT /reuniaos/1.json
  def update
    @teste=Reuniao.new(reuniao_params)
    if @reuniao.status =="finalizada"      
        redirect_to @reuniao , notice: 'Desculpe mas,reuniao finalizada não pode ser auterada.'
     
    else
    respond_to do |format|

      if @reuniao.update(reuniao_params)
        @pautum=Pautum.search(@reuniao.pautum)
        @pautum[0].status=@reuniao.status
        @pautum[0].titulo=@reuniao.titulo

        @pautum[0].save

        @atum=Atum.search(@reuniao.atum)
        @atum[0].status=@reuniao.status
        @atum[0].save
        format.html { redirect_to @reuniao, notice: 'Reuniao was successfully updated.' }
        format.json { render :show, status: :ok, location: @reuniao }
      else
        format.html { render :edit }
        format.json { render json: @reuniao.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # DELETE /reuniaos/1
  # DELETE /reuniaos/1.json
  def destroy

    if @reuniao.status=="Preparação"
      @reuniao.destroy
    respond_to do |format|
      format.html { redirect_to reuniaos_url, notice: 'Reuniao was successfully destroyed.' }
      format.json { head :no_content }
        end
    else

        redirect_to @reuniao , notice: 'Desculpe mas,reuniao já foi confirmada você não pode remove-la.'
    
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reuniao
      @reuniao = Reuniao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reuniao_params
      params.require(:reuniao).permit(:titulo, :data, :horaInicio, :horaFim, :status, :local_id, :pautum_id, :atum_id, :category_id)
    end
end

app/helpers/reuniaos_helper.rb
module ReuniaosHelper
end

app/views/reuniaos/_busca.html.erb
<%= form_tag(reuniaos_path, :method => "get") do %>

  <%= label_tag(:search_query, "Data inicio:") %>
  <%= date_field_tag :q, @search_query %>

  <%= label_tag(:search_query, "Data fim:") %>
  <%= date_field_tag :o, @search_query %>

  <%= submit_tag("Buscar") %>


<% end %>

app/views/reuniaos/_cancelar.html.erb
<%= form_for(@reuniao) do |f| %>


  <div class="field">
    <%= f.label :status %><br>
    <%= f.collection_select :status, Reuniao::Status, :to_s, :upcase %></br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reuniaos/_convocados.html.erb
<% @reuniao.convocados.each do |convocado|  %>
<p>    
 <strong>Nome:</strong>
	<%= convocado.pessoa.nome %>


 <strong>Presença confirmada ?:</strong>
	<%= convocado.presenca %>

        <% if convocado.pessoa.user != nil %>
 <strong>Papel na reunião:</strong>
	<%= convocado.pessoa.user.role %>
    <% end %>
</p>

<p>
        <% if can? :update, @convocado %>
        <td><%= link_to 'Editar', edit_convocado_path(convocado) %></td>
    <% end %>
        <% if can? :delete, @convocado %>
        <td><%= link_to 'Remover', convocado, method: :delete%></td>
    <% end %>
</p>
<p>


</p>

<% end %>

app/views/reuniaos/_form.html.erb
<%= form_for(@reuniao) do |f| %>
  <% if @reuniao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reuniao.errors.count, "error") %> prohibited this reuniao from being saved:</h2>

      <ul>
      <% @reuniao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_area :titulo %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :horaInicio %><br>
    <%= f.time_select :horaInicio %>

  </div>
  <div class="field">
    <%= f.label :horaFim %><br>
    <%= f.time_select :horaFim %>
  </div>

  <div class="field">
    <%= f.label :local_id %><br>
    <%= f.collection_select(:local_id, Local.order(:id),:id, :endereco, :prompt => true) %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select(:category_id, Category.order(:id),:id, :titulo, :prompt => true) %>
  </div>
  <div class="actions">
    <%= f.submit "Criar Reunião"%>
  </div>
<% end %>

app/views/reuniaos/_participantes.html.erb
<% @reuniao.participacaos.each do |participante|  %>
<p>    
 <strong>Nome:</strong>
	<%= participante.pessoa.nome %>
  
 <strong>contribuicão:</strong>
	<%= participante.contribuicao %>

</p>
<p>
        <% if can? :update, @participante %>
        <td><%= link_to 'Editar', edit_participacao_path(participante) %></td>
    <% end %>
        <% if can? :delete, @participante %>
        <td><%= link_to 'Remover', participante, method: :delete%></td>
    <% end %>
</p>
<% end %>

app/views/reuniaos/_search.html.erb
<%= form_tag(reuniaos_path, :method => "get") do %>

  <%= label_tag(:search_query, "Titulo:") %>
  <%= text_field_tag :p, @search_query %>
  <%= submit_tag("Buscar") %>



<% end %>

app/views/reuniaos/_sugestoes.html.erb
<% @reuniao.sugestao_item_pautums.each do |sugestao|  %>
<p>    
 <strong>Titulo: </strong>
	<%= sugestao.questao.titulo %>
</p>


<p>
        <% if can? :update, @sugestao_item_pautum %>
        <td><%= link_to 'Editar', edit_sugestao_item_pautum_path(sugestao) %></td>
    <% end %>
        <% if can? :delete, @sugestao_item_pautum %>
        <td><%= link_to 'Remover', sugestao, method: :delete%></td>
    <% end %>
</p>
<p>


</p>

<% end %>

app/views/reuniaos/edit.html.erb
<h1>Editar reunião</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @reuniao %> |

app/views/reuniaos/index.html.erb
<h1>Buscar reuniões</h1>
<%= render 'search' %>
<h3>Informe o intervalo de datas!</h3>
<%= render 'busca' %>
<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Data</th>

      <th>Inicio</th>

      <th>Termino</th>

      <th>Status</th>

      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reuniaos.each do |reuniao| %>
      <tr>
        <td><%= reuniao.titulo %></td>
        <td><%= reuniao.data.strftime("%d/%m/%Y") %></td>

        <td><%= reuniao.horaInicio.strftime('%H:%M') %></td>

        <td><%= reuniao.horaFim.strftime('%H:%M') %></td>

        <td><%= reuniao.status %></td>

        <td><%= reuniao.category.titulo %></td>
        <% if can? :read, @reuniao %>

        <td><%= link_to 'Exibir', reuniao %></td>
        <% end %>
        <% if can? :update, @reuniao %>
        <td><%= link_to 'Editar', edit_reuniao_path(reuniao) %></td>
        <% end %>
        <% if can? :delete, @reuniao %>
        <td><%= link_to 'Remover', reuniao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
        <% if can? :create, @reuniao %>

<%= link_to 'Criar Reunião', new_reuniao_path %>
        <% end %>

app/views/reuniaos/new.html.erb
<h1>Cadastro de reunião</h1>

<%= render 'form' %>

<%= link_to 'Voltar', reuniaos_path %>

app/views/reuniaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @reuniao.titulo %>
</p>

<p>
  <strong>Data:</strong>
  <%= @reuniao.data.strftime("%d/%m/%Y") %>

</p>

<p>
  <strong>Horainicio:</strong>

<%= @reuniao.horaInicio.strftime('%H:%M:%S') %>
</p>

<p>
  <strong>Horafim:</strong>

<%= @reuniao.horaFim.strftime('%H:%M:%S') %>
</p>

<p>
  <strong>Status:</strong>
  <%= @reuniao.status %>
</p>

<p>
  <strong>Local:</strong>
  <% if @reuniao.local %>
  <%= link_to 'Mais informações clique aqui', local_path(@reuniao.local) %> 
  <% end %>
</p>

<p>
  <strong>Pauta:</strong>
<%= link_to 'Clique aqui', pautum_path(@reuniao.pautum) %> 
</p>

<p>
  <strong>Ata:</strong>
<%= link_to 'Clique aqui', atum_path(@reuniao.atum) %> 
</p>

<p>

  <strong>Categoria:</strong>
  <%= @reuniao.category.titulo %>

</p>
        <% if can? :update, @reuniao %>
<%= link_to 'Editar', edit_reuniao_path(@reuniao) %> |
        <% end %>


        <% if can? :update, @reuniao %>
<h1>Atualizar status da Reunião</h1>
<%= render 'cancelar' %>
        <% end %>
<h1>Convocados para a Reunião</h1>
<%= render 'convocados' %>
        <% if can? :create, @convocado %>
                   <% if current_user.role == "coordenador" %>
<h1>Convocar</h1>

<%= link_to "Novo convocado", controller: "convocados",
action: "new",
reuniao: @reuniao %>
        <% end %>
        <% end %>



        <% if can? :create, @sugestao_item_pautum %>
                   <% if current_user.role != "admin" %>
<h1>Questões sugeridas</h1>
<%= render 'sugestoes'%>
<h1>Sugerir Questão</h1>

<%= link_to "Clik aqui", controller: "sugestao_item_pauta",
action: "new",
reuniao: @reuniao %>
        <% end %>
        <% end %>


        <% if can? :create, @participacao %>
                   <% if current_user.role == "coordenador"  %>
<h1>Inserir participantes</h1>

<%= link_to "Clik aqui", controller: "participacaos",
action: "new",
reuniao: @reuniao %>
        <% end %>
        <% end %>

<h1>Participantes da Reunião</h1>
<%= render 'participantes' %>